- name: copy catalogue service to system directory
  ansible.builtin.template:
    src: catalogue.service.j2
    dest: /etc/systemd/system/catalogue.service

- name: Reload the service
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: start and enable catalogue service
  ansible.builtin.service:
    name: catalogue 
    state: restarted
    enabled: yes